var dg_data = {
  apps: [
    {
      title: 'Web Apps',
      items: [
        ['https://www.canva.com/','Canva'],
        ['https://piktochart.com/','Piktochart'],
        ['https://infogram.com/es/','Infogram'],
        ['https://crello.com/es/home','Crello'],
        ['https://designs.ai/','Design.ai'],
        ['https://www.whatfontis.com/','WhatFontIs'],
        ['https://www.myfonts.com/WhatTheFont/','What The Font'],
        ['https://www.visme.co/','Visme'],
        ['https://www.genial.ly/es/','Genially'],
        ['https://www.figma.com/','Figma'],
        ['https://snappa.com/','Snappa'],
        ['https://www.fiverr.com/','Fiverr'],
        ['https://www.designbold.com/','Designbold'],
        ['https://www.glorify.com/pricing/','Glorify'],
        ['https://placeit.net/','Place It'],
        ['https://designer.gravit.io/','Gravit Designer PRO'],
        ['https://clipdrop.co/','Clipdrop'],
        ['http://fontastic.me/','Fontastic'],
        ['https://wordmark.it/','Wordmark'],
        ['https://studio.polotno.dev/','Polotno Studio'],
        ['https://webaim.org/resources/contrastchecker/','Contrast Checker'],
        ['https://tigrenator.com/','tigrenator | Prices'],
      ],
    },
    {
      title: 'Web Apps Photo',
      items: [
        ['https://v2.polarr.co/', 'PolarrCo'],
        ['https://raw.pics.io/', 'Pics io'],
        ['https://www.befunky.com/es/crear/editor-de-fotos/', 'BeFunky'],
        ['https://pixlr.com/es/e/','Pixlr E'],
        ['https://photopea.com/','Photopea'],
        ['https://theinpaint.com/','Inpaint'],
        ['http://www.canonoutsideofauto.ca/play/','Canon Exposure'],
        ['https://deep-image.ai/','Deep Image'],
        ['https://www.remove.bg/','Remove BG'],
        ['https://retoucher.online/','Retoucher'],
        ['https://www.watermarkremover.io/','WatermarkRemover'],
        ['https://magiceraser.io/','Magic Eraser'],
        ['https://imgupscaler.com/','AI Upscaler'],
        ['https://www.upscale.media/','Upscale Media'],
        ['http://waifu2x.udp.jp/','Waifu2x'],
        ['https://playback.fm/colorize-photo','Colorize Photo'],
        ['https://www.vectorizer.io/','Vectorizer'],
        ['https://pfpmaker.com/','Profile Picture Maker'],
        ['https://randomuser.me/','Random User Generator'],
      ],
    },
    {
      title: 'Make video',
      items: [
        ['https://www.renderforest.com/','Renderforest'],
        ['https://jitter.video/','Jitter'],
        ['https://www.powtoon.com/','Powtoon'],
        ['https://designs.ai/videomaker/start','Designs Video'],
        ['https://clipchamp.com/en/','Clipchamp'],
        ['https://www.flexclip.com/tools/screen-recorder/','Flexclip'],
        ['https://www.panopto.com/record/','Panopto'],
        ['https://www.screencapture.com/','Screencapture'],
        ['https://sketch.metademolab.com/','Animated Drawings'],
      ]
    },
    {
      title: 'Inspiración',
      items: [
        ['https://dribbble.com/','Dribbble'],
        ['https://muz.li/','Muzli'],
        ['https://es.vexels.com/','Vexels'],
        ['https://designvalley.club/','Design Valley'],
        ['https://www.awwwards.com/','Awwwards'],
        ['https://www.designspiration.net/','Designspiration'],
        ['https://www.behance.net/','Behance'],
        ['https://freebbble.com/','Freebbble'],
        ['https://ideakreativa.net/','Ideakreativa'],
        ['https://inspired360g.com/','Inspired360'],
        ['https://www.flickr.com/','Flickr'],
        ['https://fotocreativo.com/','Foto Creativo'],
        ['https://www.glamourretouchingstudio.com/','Glamour Retouching Studio'],
        ['https://www.logodesignlove.com/','LogoDesignLove'],
        ['https://theinspirationgrid.com/','Inspiration Grid'],
        ['https://www.typostrate.com/','Typostrate'],
        ['https://cosasvisuales.com/','Cosas Visuales'],
        ['https://www.logomoose.com/','Logomoose'],
        ['https://mojomox.com/','Mojomox'],
      ],
    },
    {
      title: 'Paletas',
      items: [
        ['https://colorhunt.co/','Color Hunt'],
        ['https://color.adobe.com/es/create','Adobe Color'],
        ['https://color.adobe.com/es/explore','Adobe Color Explore'],
        ['https://palettegenerator.com/','Color Palette Generator'],
        ['https://degraeve.com/color-palette/','DeGraeve'],
        ['https://www.colorzilla.com/','ColorZilla'],
        ['https://www.design-seeds.com/','Design Seeds'],
        ['https://colorschemedesigner.com/csd-3.5/','Color Scheme Designer'],
        ['https://www.colorcombos.com/combolibrary.html','Color Combo Library'],
        ['https://coolors.co/','Coolors.co'],
        ['https://colorbox.io/','ColorBox'],
      
      ],
    },
    {
      title: 'Recursos',
      items: [
        ['https://www.emprendetools.co/','EmprendeTools'],
        ['https://www.textures.com/','Textures for Photoshop'],
        ['https://iconscout.com/icons','IconScout'],
        ['https://www.flaticon.com/','Flaticon'],
        ['https://graphicburger.com/','GraphicBurger'],
        ['https://www.123freebrushes.com/','123FreeBrushes'],
        ['https://www.shapes4free.com/','Shapes4FREE'],
        ['https://freepsdvn.com/','FreePSDvn'],
        ['https://www.pinclipart.com/','Pin Clipart'],
        ['https://motionarray.com/browse/premiere-pro-templates/','Motion Array'],
        ['https://mixkit.co/','Mixkit'],
        ['https://giphy.com/','GIPHY'],
        ['https://svgporn.com/','SVG PORN'],
        ['https://uihut.com/','UIHUT'],
        ['https://logolink.com/brand/','Logolink'],
      ],
    },
    {
      title: 'Iconos Web',
      items: [
        ['https://iconos8.es/icons','Iconos'],
        ['https://icofont.com/icons','Iconfont'],
        ['https://boxicons.com/','Boxicons'],
        ['https://fontawesome.com/','Font Awesome'],
        ['https://freeicons.io/','Freeicons'],
        ['https://icons.getbootstrap.com/','Bootstrap Icons'],
        ['https://material.io/','Material Design'],
        ['https://fontello.com/','Fontello'],
        ['https://ionicons.com/','Ionicons'],
        ['http://www.entypo.com/','Entypo'],
        ['https://www.snoweb-svg.com/en/','SnoWeb'],
        ['https://iconduck.com/','Iconduck'],
        ['https://iconhub.io/','Icon Hub'],
      ],
    },
    {
      title: 'View Font',
      items: [
        ['https://fontdrop.info/','FontDrop'],
        ['https://fontsee.com/','Font see'],
        ['https://products.aspose.app/font/viewer/ttf','Font viewer'],
        ['https://fileproinfo.com/tools/viewer/woff', 'WOFF Viewer'],
      ]
    },
    {
      title: 'Tipografías',
      items: [
        ['https://www.1001fonts.com/','1001 Fonts'],
        ['https://www.canva.com/font-combinations/','Canva combination'],
        ['https://fontlibrary.org/','Font Library'],
        ['https://fonts.google.com/','Google Fonts'],
        ['https://www.dafont.com/es/','DaFont'],
        ['https://www.dafontfree.io/','Dafont Free'],
        ['https://www.urbanfonts.com/','Urban Fonts'],
        ['https://cooltext.com/','Cool Text'],
        ['https://www.myfonts.com/','MyFonts'],
        ['https://www.fontshop.com/','FontShop'],
        ['https://practicaltypography.com/','Practical Typography'],
        ['https://www.1001freefonts.com/','1001 Free Fonts'],
        ['https://www.fontsquirrel.com/','Font Squirrel'],
        ['https://www.wfonts.com/','W Fonts'],
        ['https://www.fontfabric.com/','Fontfabric'],
        ['https://velvetyne.fr/','VelveTyne'],
        ['https://fonts.adobe.com/','Adobe Fonts'],
        ['https://fontesk.com/','Fontesk'],
        ['https://befonts.com/','Befonts'],
        ['https://www.fontbrief.com/fontbrief','FontBrief'],
      ],
    },
    {
      title: 'Fotos',
      items: [
        ['https://www.everypixel.com/free','EveryPixel'],
        ['https://www.pexels.com/','Pexels'],
        ['https://pxhere.com/','PxHere'],
        ['https://www.freeimages.com/','FreeImages'],
        ['https://morguefile.com/photos/morguefile/1/pop','Morguefile'],
        ['https://littlevisuals.co/','Little Visuals'],
        ['https://stocksnap.io/','StockSnap.io'],
        ['https://unsplash.com/','Unsplash'],
        ['https://pixabay.com/','Pixabay'],
      ],
    },
    {
      title: 'Vectores',
      items: [
        ['https://fffuel.co/', 'Fffuel'],
        ['https://stonet2000.github.io/Polytomizator/','Polytomizator'],
        ['https://cojdev.github.io/lowpoly/','LowPoly Generator'],
        ['https://creazilla.com/', 'Creazilla'],
        ['https://openclipart.org/', 'OpenClicpArt'],
        ['https://www.freepik.com/','Freepik'],
        ['https://es.vecteezy.com/','Vecteezy'],
        ['https://www.iconfinder.com/','IconFinder'],
        ['https://www.123freevectors.com/','123FreeVectors'],
        ['https://www.freebiesbug.com','Freebiesbug'],
        ['https://publicdomainvectors.org/es','Publicdomainvectors'],
        ['https://tabbied.com/select-artwork','Tabbied'],
        ['https://blush.design/collections/open-peeps/open-peeps','Open Peeps'],
        ['https://undraw.co/','UnDraw']
      ],
    },
    {
      title: 'Música',
      items: [
        ['https://prosearch.tribeofnoise.com/','Tribe of Noise PRO'],
        ['https://www.jamendo.com/start','Jamendo Music'],
        ['https://musopen.org/es/music/','Musopen'],
        ['https://www.aplicacionparadescargarmusica.com/descargar-musica-sin-copyright/','Musica libre'],
        ['https://audionautix.com/','AudioNautix'],
        ['https://www.bensound.com/','Bensound'],
        ['https://www.youtube.com/user/NoCopyrightSounds','NoCopyrightSounds'],
        ['https://www.youtube.com/channel/UCEickjZj99-JJIU8_IJ7J-Q','No Copyright Music'],
        ['https://www.youtube.com/channel/UCNVgP2wjqcqJrMwOc3hOT8A','Youtuber Music'],
        ['https://www.youtube.com/channel/UC2iczXFcRRg5nN_IVQOXIaA','Chill Out Records'],
        ['https://www.youtube.com/user/FreeSongsToUse','Frequency'],
      ],
    },
    {
      title: 'Sonido',
      items: [
        ['https://www.noiseforfun.com/','NoiseForFun'],
        ['https://incompetech.com/wordpress/','Incompetech'],
        ['https://www.partnersinrhyme.com/pir/PIRsfx.shtml','Partnersinrhyme'],
        ['https://www.zapsplat.com/','ZapSplat'],
        ['https://www.flashkit.com/soundfx','Sound Fx | Flash Kit'],
        ['https://freesound.org/','Freesound'],
      ],
    },
    {
      title: 'Mockups',
      items: [
        ['https://www.mockupworld.co/','Mockup World'],
        ['https://originalmockups.com/','Original Mockups'],
        ['https://freedesignresources.net/','Free Design Resources'],
        ['https://freebbble.com/type/mockup/','Freebbble'],
        ['https://artboard.studio/','Artboard Studio'],
      ],
    },
    {
      title: 'Wallpapers',
      items: [
        ['https://www.zedge.net/','Zedge'],
        ['https://www.xtrafondos.com/','XtraFondos'],
        ['https://wallpapercave.com/','WallpaperCave'],
        ['https://wallhaven.cc/','Wallhaven'],
        ['http://wallpaperswide.com/','Wallpapers Wide'],
        ['https://wallpaperaccess.com/','Wallpapers Access'],
        ['https://www.desktopbackground.org/','Desktop Background'],  
        ['https://wallhere.com/es/','Wallhere'],
        ['https://tanck.nl/wallpaper/','Wallpaper Generator']
      ],
    },
  ],
  searchs : [
    {
      'title': 'Imágenes',
      'items': [
        ['EveryPixel', 'https://www.everypixel.com/search?q={Q}&meaning=&stocks_type=free&media_type=0&page=1'],
        ['Google', 'https://www.google.com/search?tbm=isch&q={Q}'],
        ['DuckDuckGo', 'https://duckduckgo.com/?q={Q}&ia=images&iax=images&iaf=size%3ALarge%2Clayout%3AWide'],
        ['PikPNG', 'https://www.pikpng.com/freepng/{Q}/'],
        ['PngEgg', 'https://www.pngegg.com/en/search?q={Q}'],
        ['PNGwing', 'https://www.pngwing.com/en/search?q={Q}'],
        ['Dribbble', 'https://dribbble.com/search/{Q}'],
        ['Free Images', 'https://es.freeimages.com/search/{Q}?free=1'],
        ['Pexels', 'https://www.pexels.com/search/{Q}'],
        ['PxHere', 'https://pxhere.com/es/photos?q={Q}&search='],
        ['Pixabay', 'https://pixabay.com/images/search/{Q}'],
        ['Unplash', 'https://unsplash.com/s/photos/{Q}'],
        ['Morguefile', 'https://morguefile.com/photos/morguefile/1/{Q}/pop'],
        ['All Free Download', 'https://all-free-download.com/free-photos/{Q}.html'],
        ['StockSnap', 'https://stocksnap.io/search/{Q}'],
        ['Freepik', 'https://www.freepik.com/search?dates=any&format=search&page=1&query={Q}&selection=1&sort=popular&type=photo'],
        ['The Noun Project', 'https://thenounproject.com/photos/{Q}'],
        ['Pixy', 'https://pixy.org/search.php?search={Q}']
      ]
    },
    {
      'title': 'Imágenes de pago',
      'items': [
        ['Alamy', 'https://www.alamy.com/stock-photo/man-drink.html?sortBy=relevant'],
        ['Shutterstock', 'https://www.shutterstock.com/es/search/man-drink'],
        ['123RF', 'https://www.123rf.com/stock-photo/man_drink.html'],
        ['Depositphotos', 'https://sp.depositphotos.com/stock-photos/man-drink.html?filter=all'],
        ['iStock', 'https://www.istockphoto.com/es/search/2/image?family=creative&phrase=man+drink'],
        ['Adobe Stock', 'https://stock.adobe.com/pe/search?k=man+drink&search_type=usertyped'],
        ['Freepik', 'https://www.freepik.com/search?format=search&last_filter=type&last_value=photo&query=man%20drink&type=photo']
      ]
    },
    {
      'title': 'Iconos',
      'items': [
        ['Google', 'https://www.google.com/search?tbm=isch&q={Q}&tbs=isz%3Ai'],
        ['Flaticon', 'https://www.flaticon.com/search?word={Q}'],
        ['IconScout', 'https://iconscout.com/icons/{Q}'],
        ['Vecteezy', 'https://es.vecteezy.com/vectores-gratis/{Q}?license-free=true'],
        ['Iconfinder', 'https://www.iconfinder.com/search/?q={Q}&from=homepage&price=free'],
        ['Freepik', 'https://www.freepik.com/search?dates=any&format=search&page=1&query={Q}&selection=1&sort=popular&type=icon'],
        ['Iconarchive', 'https://www.iconarchive.com/search?q={Q}'],
        ['All Free Download', 'https://www.all-free-download.com/free-icon/{Q}.html'],
        ['Publicdomainvectors', 'https://publicdomainvectors.org/en/search/{Q}'],
        ['LordIcon', 'https://lordicon.com/{Q}'],
        ['The Noun Project', 'https://thenounproject.com/icons/{Q}']
      ]
    },
    {
      'title': 'Ilustraciones',
      'items': [
        ['Pixabay', 'https://pixabay.com/vectors/search/{Q}'],
        ['IconScout', 'https://iconscout.com/illustrations/{Q}'],
        ['FreeWebIllustrations', 'https://freewebillustrations.com/search/?q={Q}'],
        ['123freevectors', 'https://www.123freevectors.com/search/{Q}'],
        ['All Free Download', 'https://all-free-download.com/free-vector/{Q}.html'],
        ['Blush', 'https://blush.design/search/{Q}']
      ]
    },
    {
      'title': 'Videos',
      'items': [
        ['Google', 'https://www.google.com/search?q={Q}+video+background'],
        ['Dribbble', 'https://dribbble.com/search/shots/popular/animation?q={Q}'],
        ['Pexels', 'https://www.pexels.com/search/videos/{Q}'],
        ['Pixabay', 'https://pixabay.com/videos/search/{Q}'],
        ['Videezy', 'https://www.videezy.com/free-video/{Q}'],
        ['Videvo', 'https://www.videvo.net/search/{Q}/clip_typeundefined/freeclips/yes/'],
        ['Coverr', 'https://coverr.co/search?q={Q}']
      ]
    },
    {
      'title': 'Plantillas',
      'items': [
        ['Motionarray', 'https://motionarray.com/browse?q={Q}&page=1'],
        ['MockupWorld', 'https://www.mockupworld.co/?s={Q}'],
        ['OriginalMockups', 'https://originalmockups.com/search?query={Q}&freebies=true'],
        ['FreeDesignreSources', 'https://freedesignresources.net/?s={Q}&post_type=post'],
        ['Freebbble', 'https://cse.google.com/cse?cx=partner-pub-1484041548332028:4502284592&ie=UTF-8&q={Q}&sa=Search&ref=www.google.com/'],
        ['Freebiesbug', 'https://freebiesbug.com/?s={Q}']
      ]
    },
    {
      'title': 'Fondos de Pantalla',
      'items': [
        ['Zedge', 'https://www.zedge.net/find/wallpapers/{Q}'],
        ['XtraFondos', 'https://www.xtrafondos.com/buscar/{Q}'],
        ['WallpaperCave', 'https://wallpapercave.com/search?q={Q}'],
        ['Wallhaven', 'https://wallhaven.cc/search?q={Q}'],
        ['All Free Download', 'https://all-free-download.com/wallpapers/{Q}.html'],
        ['Wallpapers Wide', 'http://wallpaperswide.com/search.html?q={Q}'],
        ['Wallpapers Access', 'https://wallpaperaccess.com/search?q={Q}'],
        ['Desktop Background', 'https://www.desktopbackground.org/search?kwd={Q}'],
        ['Wallhere', 'https://wallhere.com/es/wallpapers?q={Q}']
      ]
    }
  ],
  sizes: [
    ['pequeña', 640],
    ['mediana', 800],
    ['alta', 1200],
    ['grande', 1500],
    ['enorme', 2000],
    ['máxima', 'Original'],
  ],
  size_wall_dft: 640,
  h_doc: window.innerHeight + 10,
}