var dg_data = {
    apps: [
        {
            title: 'Web Apps',
            items: [
                ['https://www.canva.com/','Canva'],
                ['https://piktochart.com/','Piktochart'],
                ['https://infogram.com/es/','Infogram'],
                ['https://crello.com/es/home','Crello'],
                ['https://designs.ai/','Design.ai'],
                ['https://www.whatfontis.com/','WhatFontIs'],
                ['https://www.myfonts.com/WhatTheFont/','What The Font'],
                ['https://www.visme.co/','Visme'],
                ['https://www.genial.ly/es/','Genially'],
                ['https://www.figma.com/','Figma'],
                ['https://snappa.com/','Snappa'],
                ['https://www.fiverr.com/','Fiverr'],
                ['https://www.designbold.com/','Designbold'],
                ['https://www.glorify.com/pricing/','Glorify'],
                ['https://placeit.net/','Place It'],
                ['https://designer.gravit.io/','Gravit Designer PRO'],
                ['https://clipdrop.co/','Clipdrop'],
                ['http://fontastic.me/','Fontastic'],
                ['https://wordmark.it/','Wordmark'],
                ['https://studio.polotno.dev/','Polotno Studio'],
                ['https://webaim.org/resources/contrastchecker/','Contrast Checker'],
                ['https://tigrenator.com/','tigrenator | Prices'],
            ],
        },
        {
            title: 'Web Apps Photo',
            items: [
                ['https://v2.polarr.co/', 'PolarrCo'],
                ['https://raw.pics.io/', 'Pics io'],
                ['https://www.befunky.com/es/crear/editor-de-fotos/', 'BeFunky'],
                ['https://pixlr.com/es/e/','Pixlr E'],
                ['https://photopea.com/','Photopea'],
                ['https://theinpaint.com/','Inpaint'],
                ['http://www.canonoutsideofauto.ca/play/','Canon Exposure'],
                ['https://deep-image.ai/','Deep Image'],
                ['https://www.remove.bg/','Remove BG'],
                ['https://retoucher.online/','Retoucher'],
                ['https://www.watermarkremover.io/','WatermarkRemover'],
                ['https://magiceraser.io/','Magic Eraser'],
                ['https://imgupscaler.com/','AI Upscaler'],
                ['https://www.upscale.media/','Upscale Media'],
                ['http://waifu2x.udp.jp/','Waifu2x'],
                ['https://playback.fm/colorize-photo','Colorize Photo'],
                ['https://www.vectorizer.io/','Vectorizer'],
                ['https://pfpmaker.com/','Profile Picture Maker'],
                ['https://randomuser.me/','Random User Generator'],
            ],
        },
        {
            title: 'Make video',
            items: [
                ['https://www.renderforest.com/','Renderforest'],
                ['https://jitter.video/','Jitter'],
                ['https://www.powtoon.com/','Powtoon'],
                ['https://designs.ai/videomaker/start','Designs Video'],
                ['https://clipchamp.com/en/','Clipchamp'],
                ['https://www.flexclip.com/tools/screen-recorder/','Flexclip'],
                ['https://www.panopto.com/record/','Panopto'],
                ['https://www.screencapture.com/','Screencapture'],
                ['https://sketch.metademolab.com/','Animated Drawings'],
            ]
        },
        {
            title: 'Inspiración',
            items: [
                ['https://dribbble.com/','Dribbble'],
                ['https://muz.li/','Muzli'],
                ['https://es.vexels.com/','Vexels'],
                ['https://designvalley.club/','Design Valley'],
                ['https://www.awwwards.com/','Awwwards'],
                ['https://www.designspiration.net/','Designspiration'],
                ['https://www.behance.net/','Behance'],
                ['https://freebbble.com/','Freebbble'],
                ['https://ideakreativa.net/','Ideakreativa'],
                ['https://inspired360g.com/','Inspired360'],
                ['https://www.flickr.com/','Flickr'],
                ['https://fotocreativo.com/','Foto Creativo'],
                ['https://www.glamourretouchingstudio.com/','Glamour Retouching Studio'],
                ['https://www.logodesignlove.com/','LogoDesignLove'],
                ['https://theinspirationgrid.com/','Inspiration Grid'],
                ['https://www.typostrate.com/','Typostrate'],
                ['https://cosasvisuales.com/','Cosas Visuales'],
                ['https://www.logomoose.com/','Logomoose'],
                ['https://mojomox.com/','Mojomox'],
            ],
        },
        {
            title: 'Paletas',
            items: [
                ['https://colorhunt.co/','Color Hunt'],
                ['https://color.adobe.com/es/create','Adobe Color'],
                ['https://color.adobe.com/es/explore','Adobe Color Explore'],
                ['https://palettegenerator.com/','Color Palette Generator'],
                ['https://degraeve.com/color-palette/','DeGraeve'],
                ['https://www.colorzilla.com/','ColorZilla'],
                ['https://www.design-seeds.com/','Design Seeds'],
                ['https://colorschemedesigner.com/csd-3.5/','Color Scheme Designer'],
                ['https://www.colorcombos.com/combolibrary.html','Color Combo Library'],
                ['https://coolors.co/','Coolors.co'],
                ['https://colorbox.io/','ColorBox'],
            
            ],
        },
        {
            title: 'Recursos',
            items: [
                ['https://www.emprendetools.co/','EmprendeTools'],
                ['https://www.textures.com/','Textures for Photoshop'],
                ['https://iconscout.com/icons','IconScout'],
                ['https://www.flaticon.com/','Flaticon'],
                ['https://graphicburger.com/','GraphicBurger'],
                ['https://www.123freebrushes.com/','123FreeBrushes'],
                ['https://www.shapes4free.com/','Shapes4FREE'],
                ['https://freepsdvn.com/','FreePSDvn'],
                ['https://www.pinclipart.com/','Pin Clipart'],
                ['https://motionarray.com/browse/premiere-pro-templates/','Motion Array'],
                ['https://mixkit.co/','Mixkit'],
                ['https://giphy.com/','GIPHY'],
                ['https://svgporn.com/','SVG PORN'],
                ['https://uihut.com/','UIHUT'],
                ['https://logolink.com/brand/','Logolink'],
            ],
        },
        {
            title: 'Iconos Web',
            items: [
                ['https://iconos8.es/icons','Iconos'],
                ['https://icofont.com/icons','Iconfont'],
                ['https://boxicons.com/','Boxicons'],
                ['https://fontawesome.com/','Font Awesome'],
                ['https://freeicons.io/','Freeicons'],
                ['https://icons.getbootstrap.com/','Bootstrap Icons'],
                ['https://material.io/','Material Design'],
                ['https://fontello.com/','Fontello'],
                ['https://ionicons.com/','Ionicons'],
                ['http://www.entypo.com/','Entypo'],
                ['https://www.snoweb-svg.com/en/','SnoWeb'],
                ['https://iconduck.com/','Iconduck'],
                ['https://iconhub.io/','Icon Hub'],
            ],
        },
        {
            title: 'View Font',
            items: [
                ['https://fontdrop.info/','FontDrop'],
                ['https://fontsee.com/','Font see'],
                ['https://products.aspose.app/font/viewer/ttf','Font viewer'],
                ['https://fileproinfo.com/tools/viewer/woff', 'WOFF Viewer'],
            ]
        },
        {
            title: 'Tipografías',
            items: [
                ['https://www.1001fonts.com/','1001 Fonts'],
                ['https://www.canva.com/font-combinations/','Canva combination'],
                ['https://fontlibrary.org/','Font Library'],
                ['https://fonts.google.com/','Google Fonts'],
                ['https://www.dafont.com/es/','DaFont'],
                ['https://www.dafontfree.io/','Dafont Free'],
                ['https://www.urbanfonts.com/','Urban Fonts'],
                ['https://cooltext.com/','Cool Text'],
                ['https://www.myfonts.com/','MyFonts'],
                ['https://www.fontshop.com/','FontShop'],
                ['https://practicaltypography.com/','Practical Typography'],
                ['https://www.1001freefonts.com/','1001 Free Fonts'],
                ['https://www.fontsquirrel.com/','Font Squirrel'],
                ['https://www.wfonts.com/','W Fonts'],
                ['https://www.fontfabric.com/','Fontfabric'],
                ['https://velvetyne.fr/','VelveTyne'],
                ['https://fonts.adobe.com/','Adobe Fonts'],
                ['https://fontesk.com/','Fontesk'],
                ['https://befonts.com/','Befonts'],
            ],
        },
        {
            title: 'Fotos',
            items: [
                ['https://www.everypixel.com/free','EveryPixel'],
                ['https://www.pexels.com/','Pexels'],
                ['https://pxhere.com/','PxHere'],
                ['https://www.freeimages.com/','FreeImages'],
                ['https://morguefile.com/photos/morguefile/1/pop','Morguefile'],
                ['https://littlevisuals.co/','Little Visuals'],
                ['https://stocksnap.io/','StockSnap.io'],
                ['https://unsplash.com/','Unsplash'],
                ['https://pixabay.com/','Pixabay'],
            ],
        },
        {
            title: 'Vectores',
            items: [
                ['https://fffuel.co/', 'Fffuel'],
                ['https://stonet2000.github.io/Polytomizator/','Polytomizator'],
                ['https://cojdev.github.io/lowpoly/','LowPoly Generator'],
                ['https://creazilla.com/', 'Creazilla'],
                ['https://openclipart.org/', 'OpenClicpArt'],
                ['https://www.freepik.com/','Freepik'],
                ['https://es.vecteezy.com/','Vecteezy'],
                ['https://www.iconfinder.com/','IconFinder'],
                ['https://www.123freevectors.com/','123FreeVectors'],
                ['https://www.freebiesbug.com','Freebiesbug'],
                ['https://publicdomainvectors.org/es','Publicdomainvectors'],
                ['https://tabbied.com/select-artwork','Tabbied'],
                ['https://blush.design/collections/open-peeps/open-peeps','Open Peeps']
            ],
        },
        {
            title: 'Música',
            items: [
                ['https://prosearch.tribeofnoise.com/','Tribe of Noise PRO'],
                ['https://www.jamendo.com/start','Jamendo Music'],
                ['https://musopen.org/es/music/','Musopen'],
                ['https://www.aplicacionparadescargarmusica.com/descargar-musica-sin-copyright/','Musica libre'],
                ['https://audionautix.com/','AudioNautix'],
                ['https://www.bensound.com/','Bensound'],
                ['https://www.youtube.com/user/NoCopyrightSounds','NoCopyrightSounds'],
                ['https://www.youtube.com/channel/UCEickjZj99-JJIU8_IJ7J-Q','No Copyright Music'],
                ['https://www.youtube.com/channel/UCNVgP2wjqcqJrMwOc3hOT8A','Youtuber Music'],
                ['https://www.youtube.com/channel/UC2iczXFcRRg5nN_IVQOXIaA','Chill Out Records'],
                ['https://www.youtube.com/user/FreeSongsToUse','Frequency'],
            ],
        },
        {
            title: 'Sonido',
            items: [
                ['https://www.noiseforfun.com/','NoiseForFun'],
                ['https://incompetech.com/wordpress/','Incompetech'],
                ['https://www.partnersinrhyme.com/pir/PIRsfx.shtml','Partnersinrhyme'],
                ['https://www.zapsplat.com/','ZapSplat'],
                ['https://www.flashkit.com/soundfx','Sound Fx | Flash Kit'],
                ['https://freesound.org/','Freesound'],
            ],
        },
        {
            title: 'Mockups',
            items: [
                ['https://www.mockupworld.co/','Mockup World'],
                ['https://originalmockups.com/','Original Mockups'],
                ['https://freedesignresources.net/','Free Design Resources'],
                ['https://freebbble.com/type/mockup/','Freebbble'],
                ['https://artboard.studio/','Artboard Studio'],
            ],
        },
        {
            title: 'Wallpapers',
            items: [
                ['https://www.zedge.net/','Zedge'],
                ['https://www.xtrafondos.com/','XtraFondos'],
                ['https://wallpapercave.com/','WallpaperCave'],
                ['https://wallhaven.cc/','Wallhaven'],
                ['https://all-free-download.com/" data-src-a=".html','All Free Download'],
                ['http://wallpaperswide.com/','Wallpapers Wide'],
                ['https://wallpaperaccess.com/','Wallpapers Access'],
                ['https://www.desktopbackground.org/','Desktop Background'],    
                ['https://wallhere.com/es/','Wallhere'],
                ['https://tanck.nl/wallpaper/','Wallpaper Generator']
            ],
        },
    ],
    searchs : [
        {
            title: 'Imágenes',
            items: [
                ['https://www.everypixel.com/search?q=','&meaning=&stocks_type=free&media_type=0&page=1','EveryPixel'],
                ['https://www.google.com/search?tbm=isch&q=','Google'],
                ['https://duckduckgo.com/?q=','&ia=images&iax=images&iaf=size%3ALarge%2Clayout%3AWide','DuckDuckGo'],
                ['https://www.pikpng.com/freepng/','/','PikPNG'],
                ['https://www.pngegg.com/en/search?q=','PngEgg'],
                ['https://www.pngwing.com/en/search?q=','PNGwing'],
                ['https://dribbble.com/search/','Dribbble'],
                ['https://es.freeimages.com/search/','?free=1','Free Images'],
                ['https://www.pexels.com/search/','Pexels'],
                ['https://pxhere.com/es/photos?q=','&search=','PxHere'],
                ['https://pixabay.com/images/search/','Pixabay'],
                ['https://unsplash.com/s/photos/','Unplash'],
                ['https://morguefile.com/photos/morguefile/1/','/pop','Morguefile'],
                ['https://all-free-download.com/free-photos/','.html','All Free Download'],
                ['https://stocksnap.io/search/','StockSnap'],
                ['https://www.freepik.com/search?dates=any&format=search&page=1&query=','&selection=1&sort=popular&type=photo','Freepik'],
                ['https://thenounproject.com/photos/','The Noun Project'],
                ['https://pixy.org/search.php?search=','Pixy'],
            ],
        },
        {
            title: 'Iconos',
            items: [
                ['https://www.google.com/search?tbm=isch&q=','&tbs=isz%3Ai','Google'],
                ['https://www.flaticon.com/search?word=','Flaticon'],
                ['https://iconscout.com/icons/','IconScout'],
                ['https://es.vecteezy.com/vectores-gratis/','?license-free=true','Vecteezy'],
                ['https://www.iconfinder.com/search/?q=','&from=homepage&price=free','Iconfinder'],
                ['https://www.freepik.com/search?dates=any&format=search&page=1&query=','&selection=1&sort=popular&type=icon','Freepik'],
                ['https://www.iconarchive.com/search?q=','Iconarchive'],
                ['https://www.all-free-download.com/free-icon/','.html','All Free Download'],
                ['https://publicdomainvectors.org/en/search/','Publicdomainvectors'],
                ['https://lordicon.com/','LordIcon'],
                ['https://thenounproject.com/icons/','The Noun Project'],
            ],
        },
        {
            title: 'Ilustraciones',
            items: [
                ['https://pixabay.com/vectors/search/','Pixabay'],
                ['https://iconscout.com/illustrations/','IconScout'],
                ['https://freewebillustrations.com/search/?q=','FreeWebIllustrations'],
                ['https://www.123freevectors.com/search/','123freevectors'],
                ['https://all-free-download.com/free-vector/','.html','All Free Download'],
                ['https://blush.design/search/','Blush']
            ],
        },
        {
            title: 'Videos',
            items: [
                ['https://www.google.com/search?q=','+video+background','Google'],
                ['https://dribbble.com/search/shots/popular/animation?q=','Dribbble'],
                ['https://www.pexels.com/search/videos/','Pexels'],
                ['https://pixabay.com/videos/search/','Pixabay'],
                ['https://www.videezy.com/free-video/','Videezy'],
                ['https://www.videvo.net/search/','/clip_typeundefined/freeclips/yes/','Videvo'],
                ['https://coverr.co/search?q=','Coverr'],
            ],
        },
        {
            title: 'Plantillas',
            items: [
                ['https://motionarray.com/browse?q=','&page=1','Motionarray'],
                ['https://www.mockupworld.co/?s=','MockupWorld'],
                ['https://originalmockups.com/search?query=','&freebies=true','OriginalMockups'],
                ['https://freedesignresources.net/?s=','&post_type=post','FreeDesignreSources'],
                ['https://cse.google.com/cse?cx=partner-pub-1484041548332028:4502284592&ie=UTF-8&q=','&sa=Search&ref=www.google.com/','Freebbble'],
                ['https://freebiesbug.com/?s=','Freebiesbug'],
            ],
        },
        {
            title: 'Fondos de Pantalla',
            items: [
                ['https://www.zedge.net/find/wallpapers/','Zedge'],
                ['https://www.xtrafondos.com/buscar/','XtraFondos'],
                ['https://wallpapercave.com/search?q=','WallpaperCave'],
                ['https://wallhaven.cc/search?q=','Wallhaven'],
                ['https://all-free-download.com/wallpapers/','.html','All Free Download'],
                ['http://wallpaperswide.com/search.html?q=','Wallpapers Wide'],
                ['https://wallpaperaccess.com/search?q=','Wallpapers Access'],
                ['https://www.desktopbackground.org/search?kwd=','Desktop Background'],
                ['https://wallhere.com/es/wallpapers?q=','Wallhere'],
            ],
        },
    ],
    sizes: [
        ['pequeña',640],
        ['mediana',800],
        ['alta',1200],
        ['grande',1500],
        ['enorme',2000],
        ['máxima','Original'],
    ],
    size_wall_dft: 640,
    h_doc: window.innerHeight + 10,
}